/* Generated by re2c 0.14.3 on Sat Sep 23 14:14:03 2017 */
#line 1 "scanner.re"

#include <string.h>
#include "mk.h"
#include "scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int mk_get_token(mk_scanner_state *s, mk_scanner_token *token) {

	char *q = YYCURSOR, *start = YYCURSOR;
	int status = MK_SCANNER_RETCODE_IMPOSSIBLE;
	int is_constant = 0, j;

	while (MK_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
#line 23 "scanner.c"
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy69;
			case '\t':
			case '\r':
			case ' ':	goto yy65;
			case '\n':	goto yy67;
			case '!':	goto yy33;
			case '"':	goto yy15;
			case '$':	goto yy16;
			case '%':	goto yy53;
			case '&':	goto yy35;
			case '\'':	goto yy11;
			case '(':	goto yy19;
			case ')':	goto yy21;
			case '*':	goto yy49;
			case '+':	goto yy47;
			case ',':	goto yy61;
			case '-':	goto yy2;
			case '.':	goto yy55;
			case '/':	goto yy51;
			case '0':	goto yy4;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy6;
			case ':':	goto yy57;
			case ';':	goto yy59;
			case '<':	goto yy41;
			case '=':	goto yy45;
			case '>':	goto yy43;
			case '?':	goto yy63;
			case '@':	goto yy31;
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy18;
			case 'F':
			case 'f':	goto yy9;
			case 'N':
			case 'n':	goto yy7;
			case 'T':
			case 't':	goto yy10;
			case '[':	goto yy27;
			case '\\':
			case '_':	goto yy17;
			case ']':	goto yy29;
			case '^':	goto yy39;
			case '{':	goto yy23;
			case '|':	goto yy37;
			case '}':	goto yy25;
			case '~':	goto yy13;
			default:	goto yy71;
			}
yy2:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '-':	goto yy154;
			case '0':	goto yy160;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy146;
			case '=':	goto yy158;
			case '>':	goto yy156;
			default:	goto yy3;
			}
yy3:
#line 318 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SUB;
			return 0;
		}
#line 154 "scanner.c"
yy4:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case 'x':	goto yy151;
			default:	goto yy147;
			}
yy5:
#line 24 "scanner.re"
			{
			token->opcode = MK_T_INTEGER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 172 "scanner.c"
yy6:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			goto yy147;
yy7:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case 'U':
			case 'u':	goto yy141;
			default:	goto yy115;
			}
yy8:
#line 93 "scanner.re"
			{
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			token->opcode = MK_T_IDENTIFIER;
			return 0;
		}
#line 194 "scanner.c"
yy9:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy136;
			default:	goto yy115;
			}
yy10:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy132;
			default:	goto yy115;
			}
yy11:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych >= 0x01) goto yy128;
yy12:
#line 408 "scanner.re"
			{
			status = MK_SCANNER_RETCODE_ERR;
			break;
		}
#line 219 "scanner.c"
yy13:
			yyaccept = 2;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case '"':	goto yy122;
			default:	goto yy14;
			}
yy14:
#line 150 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_NOT;
			return 0;
		}
#line 234 "scanner.c"
yy15:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy12;
			goto yy117;
yy16:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy114;
			default:	goto yy12;
			}
yy17:
			yych = *++YYCURSOR;
			goto yy115;
yy18:
			yych = *++YYCURSOR;
			goto yy115;
yy19:
			++YYCURSOR;
#line 102 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_PARENTHESES_OPEN;
			return 0;
		}
#line 313 "scanner.c"
yy21:
			++YYCURSOR;
#line 108 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_PARENTHESES_CLOSE;
			return 0;
		}
#line 322 "scanner.c"
yy23:
			++YYCURSOR;
#line 114 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BRACKET_OPEN;
			return 0;
		}
#line 331 "scanner.c"
yy25:
			++YYCURSOR;
#line 120 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BRACKET_CLOSE;
			return 0;
		}
#line 340 "scanner.c"
yy27:
			++YYCURSOR;
#line 126 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SBRACKET_OPEN;
			return 0;
		}
#line 349 "scanner.c"
yy29:
			++YYCURSOR;
#line 132 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SBRACKET_CLOSE;
			return 0;
		}
#line 358 "scanner.c"
yy31:
			++YYCURSOR;
#line 138 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_AT;
			return 0;
		}
#line 367 "scanner.c"
yy33:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy110;
			default:	goto yy34;
			}
yy34:
#line 144 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_NOT;
			return 0;
		}
#line 381 "scanner.c"
yy35:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '&':	goto yy108;
			default:	goto yy36;
			}
yy36:
#line 168 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_AND;
			return 0;
		}
#line 395 "scanner.c"
yy37:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '|':	goto yy106;
			default:	goto yy38;
			}
yy38:
#line 174 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_OR;
			return 0;
		}
#line 409 "scanner.c"
yy39:
			++YYCURSOR;
#line 180 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_XOR;
			return 0;
		}
#line 418 "scanner.c"
yy41:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '<':	goto yy104;
			case '=':	goto yy102;
			default:	goto yy42;
			}
yy42:
#line 276 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_LESS;
			return 0;
		}
#line 433 "scanner.c"
yy43:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy98;
			case '>':	goto yy100;
			default:	goto yy44;
			}
yy44:
#line 282 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_GREATER;
			return 0;
		}
#line 448 "scanner.c"
yy45:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy94;
			case '>':	goto yy92;
			default:	goto yy46;
			}
yy46:
#line 198 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_ASSIGN;
			return 0;
		}
#line 463 "scanner.c"
yy47:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '+':	goto yy88;
			case '=':	goto yy90;
			default:	goto yy48;
			}
yy48:
#line 312 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_ADD;
			return 0;
		}
#line 478 "scanner.c"
yy49:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy86;
			default:	goto yy50;
			}
yy50:
#line 324 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MUL;
			return 0;
		}
#line 492 "scanner.c"
yy51:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy84;
			default:	goto yy52;
			}
yy52:
#line 330 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DIV;
			return 0;
		}
#line 506 "scanner.c"
yy53:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy82;
			default:	goto yy54;
			}
yy54:
#line 336 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MOD;
			return 0;
		}
#line 520 "scanner.c"
yy55:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '.':	goto yy76;
			case '=':	goto yy78;
			default:	goto yy56;
			}
yy56:
#line 306 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DOT;
			return 0;
		}
#line 535 "scanner.c"
yy57:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case ':':	goto yy74;
			default:	goto yy58;
			}
yy58:
#line 366 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_COLON;
			return 0;
		}
#line 549 "scanner.c"
yy59:
			++YYCURSOR;
#line 372 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DOTCOMMA;
			return 0;
		}
#line 558 "scanner.c"
yy61:
			++YYCURSOR;
#line 378 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_COMMA;
			return 0;
		}
#line 567 "scanner.c"
yy63:
			++YYCURSOR;
#line 384 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_QUESTION;
			return 0;
		}
#line 576 "scanner.c"
yy65:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy73;
yy66:
#line 390 "scanner.re"
			{
			s->active_char += (YYCURSOR - start);
			token->opcode = MK_T_IGNORE;
			return 0;
		}
#line 588 "scanner.c"
yy67:
			++YYCURSOR;
#line 396 "scanner.re"
			{
			s->active_line++;
			s->active_char = 0;
			token->opcode = MK_T_IGNORE;
			return 0;
		}
#line 598 "scanner.c"
yy69:
			++YYCURSOR;
#line 403 "scanner.re"
			{
			status = MK_SCANNER_RETCODE_EOF;
			break;
		}
#line 606 "scanner.c"
yy71:
			yych = *++YYCURSOR;
			goto yy12;
yy72:
			++YYCURSOR;
			yych = *YYCURSOR;
yy73:
			switch (yych) {
			case '\t':
			case '\r':
			case ' ':	goto yy72;
			default:	goto yy66;
			}
yy74:
			++YYCURSOR;
#line 300 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_DOUBLECOLON;
			return 0;
		}
#line 628 "scanner.c"
yy76:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '.':	goto yy80;
			default:	goto yy77;
			}
yy77:
#line 354 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_INCLUSIVE_RANGE;
			return 0;
		}
#line 642 "scanner.c"
yy78:
			++YYCURSOR;
#line 234 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_CONCATASSIGN;
			return 0;
		}
#line 651 "scanner.c"
yy80:
			++YYCURSOR;
#line 360 "scanner.re"
			{
			s->active_char += 3;
			token->opcode = MK_T_EXCLUSIVE_RANGE;
			return 0;
		}
#line 660 "scanner.c"
yy82:
			++YYCURSOR;
#line 228 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MODASSIGN;
			return 0;
		}
#line 669 "scanner.c"
yy84:
			++YYCURSOR;
#line 222 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DIVASSIGN;
			return 0;
		}
#line 678 "scanner.c"
yy86:
			++YYCURSOR;
#line 216 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MULASSIGN;
			return 0;
		}
#line 687 "scanner.c"
yy88:
			++YYCURSOR;
#line 342 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_INCR;
			return 0;
		}
#line 696 "scanner.c"
yy90:
			++YYCURSOR;
#line 204 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_ADDASSIGN;
			return 0;
		}
#line 705 "scanner.c"
yy92:
			++YYCURSOR;
#line 294 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_DOUBLEARROW;
			return 0;
		}
#line 714 "scanner.c"
yy94:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy96;
			default:	goto yy95;
			}
yy95:
#line 240 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_EQUALS;
			return 0;
		}
#line 728 "scanner.c"
yy96:
			++YYCURSOR;
#line 252 "scanner.re"
			{
			s->active_char += 3;
			token->opcode = MK_T_IDENTICAL;
			return 0;
		}
#line 737 "scanner.c"
yy98:
			++YYCURSOR;
#line 270 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_GREATEREQUAL;
			return 0;
		}
#line 746 "scanner.c"
yy100:
			++YYCURSOR;
#line 192 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_BITWISE_SHIFTRIGHT;
			return 0;
		}
#line 755 "scanner.c"
yy102:
			++YYCURSOR;
#line 264 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_LESSEQUAL;
			return 0;
		}
#line 764 "scanner.c"
yy104:
			++YYCURSOR;
#line 186 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_BITWISE_SHIFTLEFT;
			return 0;
		}
#line 773 "scanner.c"
yy106:
			++YYCURSOR;
#line 162 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_OR;
			return 0;
		}
#line 782 "scanner.c"
yy108:
			++YYCURSOR;
#line 156 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_AND;
			return 0;
		}
#line 791 "scanner.c"
yy110:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy112;
			default:	goto yy111;
			}
yy111:
#line 246 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_NOTEQUALS;
			return 0;
		}
#line 805 "scanner.c"
yy112:
			++YYCURSOR;
#line 258 "scanner.re"
			{
			s->active_char += 3;
			token->opcode = MK_T_NOTIDENTICAL;
			return 0;
		}
#line 814 "scanner.c"
yy114:
			++YYCURSOR;
			yych = *YYCURSOR;
yy115:
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy114;
			default:	goto yy8;
			}
yy116:
			++YYCURSOR;
			yych = *YYCURSOR;
yy117:
			switch (yych) {
			case 0x00:	goto yy118;
			case '"':	goto yy120;
			case '\\':	goto yy119;
			default:	goto yy116;
			}
yy118:
			YYCURSOR = YYMARKER;
			switch (yyaccept) {
			case 0: 	goto yy5;
			case 1: 	goto yy12;
			default:	goto yy14;
			}
yy119:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy118;
			default:	goto yy116;
			}
yy120:
			++YYCURSOR;
#line 82 "scanner.re"
			{
			token->opcode = MK_T_STRING;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 921 "scanner.c"
yy122:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy118;
			case '"':	goto yy125;
			case '\\':	goto yy124;
			default:	goto yy122;
			}
yy124:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy118;
			default:	goto yy122;
			}
yy125:
			++YYCURSOR;
#line 72 "scanner.re"
			{
			token->opcode = MK_T_ISTRING;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 949 "scanner.c"
yy127:
			++YYCURSOR;
			yych = *YYCURSOR;
yy128:
			switch (yych) {
			case 0x00:	goto yy118;
			case '\'':	goto yy130;
			case '\\':	goto yy129;
			default:	goto yy127;
			}
yy129:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy118;
			default:	goto yy127;
			}
yy130:
			++YYCURSOR;
#line 62 "scanner.re"
			{
			token->opcode = MK_T_CHAR;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 978 "scanner.c"
yy132:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy133;
			default:	goto yy115;
			}
yy133:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy134;
			default:	goto yy115;
			}
yy134:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy114;
			default:	goto yy135;
			}
yy135:
#line 55 "scanner.re"
			{
			s->active_char += sizeof("true")-1;
			token->opcode = MK_T_TRUE;
			return 0;
		}
#line 1069 "scanner.c"
yy136:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy137;
			default:	goto yy115;
			}
yy137:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy138;
			default:	goto yy115;
			}
yy138:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy139;
			default:	goto yy115;
			}
yy139:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy114;
			default:	goto yy140;
			}
yy140:
#line 49 "scanner.re"
			{
			s->active_char += sizeof("false")-1;
			token->opcode = MK_T_FALSE;
			return 0;
		}
#line 1167 "scanner.c"
yy141:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy142;
			default:	goto yy115;
			}
yy142:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy143;
			default:	goto yy115;
			}
yy143:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy114;
			default:	goto yy144;
			}
yy144:
#line 43 "scanner.re"
			{
			s->active_char += sizeof("null")-1;
			token->opcode = MK_T_NULL;
			return 0;
		}
#line 1258 "scanner.c"
yy145:
			yych = *++YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy148;
			default:	goto yy118;
			}
yy146:
			yyaccept = 0;
			YYMARKER = ++YYCURSOR;
			yych = *YYCURSOR;
yy147:
			switch (yych) {
			case '.':	goto yy145;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy146;
			default:	goto yy5;
			}
yy148:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy148;
			default:	goto yy150;
			}
yy150:
#line 34 "scanner.re"
			{
			token->opcode = MK_T_DOUBLE;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 1319 "scanner.c"
yy151:
			yych = *++YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':	goto yy152;
			default:	goto yy118;
			}
yy152:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':	goto yy152;
			default:	goto yy5;
			}
yy154:
			++YYCURSOR;
#line 348 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_DECR;
			return 0;
		}
#line 1383 "scanner.c"
yy156:
			++YYCURSOR;
#line 288 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_ARROW;
			return 0;
		}
#line 1392 "scanner.c"
yy158:
			++YYCURSOR;
#line 210 "scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SUBASSIGN;
			return 0;
		}
#line 1401 "scanner.c"
yy160:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case 'x':	goto yy151;
			default:	goto yy147;
			}
		}
#line 413 "scanner.re"

	}

	return status;
}
