#define MK_USE                             1
#define MK_IDENTIFIER                      2
#define MK_INSERT                          3
#define MK_INTO                            4
#define MK_VALUES                          5
#define MK_PARENTHESES_OPEN                6
#define MK_PARENTHESES_CLOSE               7
#define MK_DROP                            8
#define MK_COLLECTION                      9
#define MK_IF                             10
#define MK_EXISTS                         11
#define MK_CREATE                         12
#define MK_COMMA                          13
#define MK_INTEGER                        14
