#define MK_USE                             1
#define MK_IDENTIFIER                      2
#define MK_INSERT                          3
#define MK_INTO                            4
#define MK_VALUES                          5
#define MK_PARENTHESES_OPEN                6
#define MK_PARENTHESES_CLOSE               7
#define MK_CREATE                          8
#define MK_COLLECTION                      9
#define MK_COMMA                          10
#define MK_INTEGER                        11
