/* Generated by re2c 0.14.3 on Sat Sep 23 22:18:59 2017 */
#line 1 "src/parser/scanner.re"

#include <string.h>
#include "../mk.h"
#include "scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int mk_get_token(mk_scanner_state *s, mk_scanner_token *token) {

	char *q = YYCURSOR, *start = YYCURSOR;
	int status = MK_SCANNER_RETCODE_IMPOSSIBLE;
	int is_constant = 0, j;

	while (MK_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
#line 23 "src/parser/scanner.c"
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy74;
			case '\t':
			case '\r':
			case ' ':	goto yy70;
			case '\n':	goto yy72;
			case '!':	goto yy38;
			case '"':	goto yy20;
			case '$':	goto yy21;
			case '%':	goto yy58;
			case '&':	goto yy40;
			case '\'':	goto yy16;
			case '(':	goto yy24;
			case ')':	goto yy26;
			case '*':	goto yy54;
			case '+':	goto yy52;
			case ',':	goto yy66;
			case '-':	goto yy2;
			case '.':	goto yy60;
			case '/':	goto yy56;
			case '0':	goto yy4;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy6;
			case ':':	goto yy62;
			case ';':	goto yy64;
			case '<':	goto yy46;
			case '=':	goto yy50;
			case '>':	goto yy48;
			case '?':	goto yy68;
			case '@':	goto yy36;
			case 'A':
			case 'B':
			case 'E':
			case 'G':
			case 'H':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'b':
			case 'e':
			case 'g':
			case 'h':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy23;
			case 'C':
			case 'c':	goto yy13;
			case 'D':
			case 'd':	goto yy15;
			case 'F':
			case 'f':	goto yy9;
			case 'I':
			case 'i':	goto yy11;
			case 'N':
			case 'n':	goto yy7;
			case 'T':
			case 't':	goto yy10;
			case 'U':
			case 'u':	goto yy14;
			case 'V':
			case 'v':	goto yy12;
			case '[':	goto yy32;
			case '\\':
			case '_':	goto yy22;
			case ']':	goto yy34;
			case '^':	goto yy44;
			case '{':	goto yy28;
			case '|':	goto yy42;
			case '}':	goto yy30;
			case '~':	goto yy18;
			default:	goto yy76;
			}
yy2:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '-':	goto yy201;
			case '0':	goto yy207;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy193;
			case '=':	goto yy205;
			case '>':	goto yy203;
			default:	goto yy3;
			}
yy3:
#line 360 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SUB;
			return 0;
		}
#line 154 "src/parser/scanner.c"
yy4:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case 'x':	goto yy198;
			default:	goto yy194;
			}
yy5:
#line 24 "src/parser/scanner.re"
			{
			token->opcode = MK_T_INTEGER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 172 "src/parser/scanner.c"
yy6:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			goto yy194;
yy7:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case 'U':
			case 'u':	goto yy188;
			default:	goto yy120;
			}
yy8:
#line 135 "src/parser/scanner.re"
			{
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			token->opcode = MK_T_IDENTIFIER;
			return 0;
		}
#line 194 "src/parser/scanner.c"
yy9:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy183;
			default:	goto yy120;
			}
yy10:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy179;
			default:	goto yy120;
			}
yy11:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy170;
			default:	goto yy120;
			}
yy12:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy164;
			default:	goto yy120;
			}
yy13:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy148;
			case 'R':
			case 'r':	goto yy149;
			default:	goto yy120;
			}
yy14:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy145;
			default:	goto yy120;
			}
yy15:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy137;
			default:	goto yy120;
			}
yy16:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych >= 0x01) goto yy133;
yy17:
#line 450 "src/parser/scanner.re"
			{
			status = MK_SCANNER_RETCODE_ERR;
			break;
		}
#line 256 "src/parser/scanner.c"
yy18:
			yyaccept = 2;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case '"':	goto yy127;
			default:	goto yy19;
			}
yy19:
#line 192 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_NOT;
			return 0;
		}
#line 271 "src/parser/scanner.c"
yy20:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy17;
			goto yy122;
yy21:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy17;
			}
yy22:
			yych = *++YYCURSOR;
			goto yy120;
yy23:
			yych = *++YYCURSOR;
			goto yy120;
yy24:
			++YYCURSOR;
#line 144 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_PARENTHESES_OPEN;
			return 0;
		}
#line 350 "src/parser/scanner.c"
yy26:
			++YYCURSOR;
#line 150 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_PARENTHESES_CLOSE;
			return 0;
		}
#line 359 "src/parser/scanner.c"
yy28:
			++YYCURSOR;
#line 156 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BRACKET_OPEN;
			return 0;
		}
#line 368 "src/parser/scanner.c"
yy30:
			++YYCURSOR;
#line 162 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BRACKET_CLOSE;
			return 0;
		}
#line 377 "src/parser/scanner.c"
yy32:
			++YYCURSOR;
#line 168 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SBRACKET_OPEN;
			return 0;
		}
#line 386 "src/parser/scanner.c"
yy34:
			++YYCURSOR;
#line 174 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SBRACKET_CLOSE;
			return 0;
		}
#line 395 "src/parser/scanner.c"
yy36:
			++YYCURSOR;
#line 180 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_AT;
			return 0;
		}
#line 404 "src/parser/scanner.c"
yy38:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy115;
			default:	goto yy39;
			}
yy39:
#line 186 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_NOT;
			return 0;
		}
#line 418 "src/parser/scanner.c"
yy40:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '&':	goto yy113;
			default:	goto yy41;
			}
yy41:
#line 210 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_AND;
			return 0;
		}
#line 432 "src/parser/scanner.c"
yy42:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '|':	goto yy111;
			default:	goto yy43;
			}
yy43:
#line 216 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_OR;
			return 0;
		}
#line 446 "src/parser/scanner.c"
yy44:
			++YYCURSOR;
#line 222 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_XOR;
			return 0;
		}
#line 455 "src/parser/scanner.c"
yy46:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '<':	goto yy109;
			case '=':	goto yy107;
			default:	goto yy47;
			}
yy47:
#line 318 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_LESS;
			return 0;
		}
#line 470 "src/parser/scanner.c"
yy48:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy103;
			case '>':	goto yy105;
			default:	goto yy49;
			}
yy49:
#line 324 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_GREATER;
			return 0;
		}
#line 485 "src/parser/scanner.c"
yy50:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy99;
			case '>':	goto yy97;
			default:	goto yy51;
			}
yy51:
#line 240 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_ASSIGN;
			return 0;
		}
#line 500 "src/parser/scanner.c"
yy52:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '+':	goto yy93;
			case '=':	goto yy95;
			default:	goto yy53;
			}
yy53:
#line 354 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_ADD;
			return 0;
		}
#line 515 "src/parser/scanner.c"
yy54:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy91;
			default:	goto yy55;
			}
yy55:
#line 366 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MUL;
			return 0;
		}
#line 529 "src/parser/scanner.c"
yy56:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy89;
			default:	goto yy57;
			}
yy57:
#line 372 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DIV;
			return 0;
		}
#line 543 "src/parser/scanner.c"
yy58:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy87;
			default:	goto yy59;
			}
yy59:
#line 378 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MOD;
			return 0;
		}
#line 557 "src/parser/scanner.c"
yy60:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '.':	goto yy81;
			case '=':	goto yy83;
			default:	goto yy61;
			}
yy61:
#line 348 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DOT;
			return 0;
		}
#line 572 "src/parser/scanner.c"
yy62:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case ':':	goto yy79;
			default:	goto yy63;
			}
yy63:
#line 408 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_COLON;
			return 0;
		}
#line 586 "src/parser/scanner.c"
yy64:
			++YYCURSOR;
#line 414 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DOTCOMMA;
			return 0;
		}
#line 595 "src/parser/scanner.c"
yy66:
			++YYCURSOR;
#line 420 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_COMMA;
			return 0;
		}
#line 604 "src/parser/scanner.c"
yy68:
			++YYCURSOR;
#line 426 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_QUESTION;
			return 0;
		}
#line 613 "src/parser/scanner.c"
yy70:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy78;
yy71:
#line 432 "src/parser/scanner.re"
			{
			s->active_char += (YYCURSOR - start);
			token->opcode = MK_T_IGNORE;
			return 0;
		}
#line 625 "src/parser/scanner.c"
yy72:
			++YYCURSOR;
#line 438 "src/parser/scanner.re"
			{
			s->active_line++;
			s->active_char = 0;
			token->opcode = MK_T_IGNORE;
			return 0;
		}
#line 635 "src/parser/scanner.c"
yy74:
			++YYCURSOR;
#line 445 "src/parser/scanner.re"
			{
			status = MK_SCANNER_RETCODE_EOF;
			break;
		}
#line 643 "src/parser/scanner.c"
yy76:
			yych = *++YYCURSOR;
			goto yy17;
yy77:
			++YYCURSOR;
			yych = *YYCURSOR;
yy78:
			switch (yych) {
			case '\t':
			case '\r':
			case ' ':	goto yy77;
			default:	goto yy71;
			}
yy79:
			++YYCURSOR;
#line 342 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_DOUBLECOLON;
			return 0;
		}
#line 665 "src/parser/scanner.c"
yy81:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '.':	goto yy85;
			default:	goto yy82;
			}
yy82:
#line 396 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_INCLUSIVE_RANGE;
			return 0;
		}
#line 679 "src/parser/scanner.c"
yy83:
			++YYCURSOR;
#line 276 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_CONCATASSIGN;
			return 0;
		}
#line 688 "src/parser/scanner.c"
yy85:
			++YYCURSOR;
#line 402 "src/parser/scanner.re"
			{
			s->active_char += 3;
			token->opcode = MK_T_EXCLUSIVE_RANGE;
			return 0;
		}
#line 697 "src/parser/scanner.c"
yy87:
			++YYCURSOR;
#line 270 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MODASSIGN;
			return 0;
		}
#line 706 "src/parser/scanner.c"
yy89:
			++YYCURSOR;
#line 264 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DIVASSIGN;
			return 0;
		}
#line 715 "src/parser/scanner.c"
yy91:
			++YYCURSOR;
#line 258 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MULASSIGN;
			return 0;
		}
#line 724 "src/parser/scanner.c"
yy93:
			++YYCURSOR;
#line 384 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_INCR;
			return 0;
		}
#line 733 "src/parser/scanner.c"
yy95:
			++YYCURSOR;
#line 246 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_ADDASSIGN;
			return 0;
		}
#line 742 "src/parser/scanner.c"
yy97:
			++YYCURSOR;
#line 336 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_DOUBLEARROW;
			return 0;
		}
#line 751 "src/parser/scanner.c"
yy99:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy101;
			default:	goto yy100;
			}
yy100:
#line 282 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_EQUALS;
			return 0;
		}
#line 765 "src/parser/scanner.c"
yy101:
			++YYCURSOR;
#line 294 "src/parser/scanner.re"
			{
			s->active_char += 3;
			token->opcode = MK_T_IDENTICAL;
			return 0;
		}
#line 774 "src/parser/scanner.c"
yy103:
			++YYCURSOR;
#line 312 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_GREATEREQUAL;
			return 0;
		}
#line 783 "src/parser/scanner.c"
yy105:
			++YYCURSOR;
#line 234 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_BITWISE_SHIFTRIGHT;
			return 0;
		}
#line 792 "src/parser/scanner.c"
yy107:
			++YYCURSOR;
#line 306 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_LESSEQUAL;
			return 0;
		}
#line 801 "src/parser/scanner.c"
yy109:
			++YYCURSOR;
#line 228 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_BITWISE_SHIFTLEFT;
			return 0;
		}
#line 810 "src/parser/scanner.c"
yy111:
			++YYCURSOR;
#line 204 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_OR;
			return 0;
		}
#line 819 "src/parser/scanner.c"
yy113:
			++YYCURSOR;
#line 198 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_AND;
			return 0;
		}
#line 828 "src/parser/scanner.c"
yy115:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy117;
			default:	goto yy116;
			}
yy116:
#line 288 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_NOTEQUALS;
			return 0;
		}
#line 842 "src/parser/scanner.c"
yy117:
			++YYCURSOR;
#line 300 "src/parser/scanner.re"
			{
			s->active_char += 3;
			token->opcode = MK_T_NOTIDENTICAL;
			return 0;
		}
#line 851 "src/parser/scanner.c"
yy119:
			++YYCURSOR;
			yych = *YYCURSOR;
yy120:
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy8;
			}
yy121:
			++YYCURSOR;
			yych = *YYCURSOR;
yy122:
			switch (yych) {
			case 0x00:	goto yy123;
			case '"':	goto yy125;
			case '\\':	goto yy124;
			default:	goto yy121;
			}
yy123:
			YYCURSOR = YYMARKER;
			switch (yyaccept) {
			case 0: 	goto yy5;
			case 1: 	goto yy17;
			default:	goto yy19;
			}
yy124:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy123;
			default:	goto yy121;
			}
yy125:
			++YYCURSOR;
#line 124 "src/parser/scanner.re"
			{
			token->opcode = MK_T_STRING;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 958 "src/parser/scanner.c"
yy127:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy123;
			case '"':	goto yy130;
			case '\\':	goto yy129;
			default:	goto yy127;
			}
yy129:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy123;
			default:	goto yy127;
			}
yy130:
			++YYCURSOR;
#line 114 "src/parser/scanner.re"
			{
			token->opcode = MK_T_ISTRING;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 986 "src/parser/scanner.c"
yy132:
			++YYCURSOR;
			yych = *YYCURSOR;
yy133:
			switch (yych) {
			case 0x00:	goto yy123;
			case '\'':	goto yy135;
			case '\\':	goto yy134;
			default:	goto yy132;
			}
yy134:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy123;
			default:	goto yy132;
			}
yy135:
			++YYCURSOR;
#line 104 "src/parser/scanner.re"
			{
			token->opcode = MK_T_CHAR;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 1015 "src/parser/scanner.c"
yy137:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy138;
			default:	goto yy120;
			}
yy138:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy139;
			default:	goto yy120;
			}
yy139:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy140;
			default:	goto yy120;
			}
yy140:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy141;
			default:	goto yy120;
			}
yy141:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy142;
			default:	goto yy120;
			}
yy142:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy143;
			default:	goto yy120;
			}
yy143:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy144;
			}
yy144:
#line 97 "src/parser/scanner.re"
			{
			s->active_char += sizeof("database")-1;
			token->opcode = MK_T_DATABASE;
			return 0;
		}
#line 1134 "src/parser/scanner.c"
yy145:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy146;
			default:	goto yy120;
			}
yy146:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy147;
			}
yy147:
#line 91 "src/parser/scanner.re"
			{
			s->active_char += sizeof("use")-1;
			token->opcode = MK_T_USE;
			return 0;
		}
#line 1218 "src/parser/scanner.c"
yy148:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy155;
			default:	goto yy120;
			}
yy149:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy150;
			default:	goto yy120;
			}
yy150:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy151;
			default:	goto yy120;
			}
yy151:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy152;
			default:	goto yy120;
			}
yy152:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy153;
			default:	goto yy120;
			}
yy153:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy154;
			}
yy154:
#line 79 "src/parser/scanner.re"
			{
			s->active_char += sizeof("create")-1;
			token->opcode = MK_T_CREATE;
			return 0;
		}
#line 1330 "src/parser/scanner.c"
yy155:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy156;
			default:	goto yy120;
			}
yy156:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy157;
			default:	goto yy120;
			}
yy157:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy158;
			default:	goto yy120;
			}
yy158:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy159;
			default:	goto yy120;
			}
yy159:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy160;
			default:	goto yy120;
			}
yy160:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy161;
			default:	goto yy120;
			}
yy161:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy162;
			default:	goto yy120;
			}
yy162:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy163;
			}
yy163:
#line 85 "src/parser/scanner.re"
			{
			s->active_char += sizeof("collection")-1;
			token->opcode = MK_T_COLLECTION;
			return 0;
		}
#line 1456 "src/parser/scanner.c"
yy164:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy165;
			default:	goto yy120;
			}
yy165:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy166;
			default:	goto yy120;
			}
yy166:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy167;
			default:	goto yy120;
			}
yy167:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy168;
			default:	goto yy120;
			}
yy168:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy169;
			}
yy169:
#line 73 "src/parser/scanner.re"
			{
			s->active_char += sizeof("values")-1;
			token->opcode = MK_T_VALUES;
			return 0;
		}
#line 1561 "src/parser/scanner.c"
yy170:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy171;
			case 'T':
			case 't':	goto yy172;
			default:	goto yy120;
			}
yy171:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy175;
			default:	goto yy120;
			}
yy172:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy173;
			default:	goto yy120;
			}
yy173:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy174;
			}
yy174:
#line 67 "src/parser/scanner.re"
			{
			s->active_char += sizeof("into")-1;
			token->opcode = MK_T_INTO;
			return 0;
		}
#line 1661 "src/parser/scanner.c"
yy175:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy176;
			default:	goto yy120;
			}
yy176:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy177;
			default:	goto yy120;
			}
yy177:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy178;
			}
yy178:
#line 61 "src/parser/scanner.re"
			{
			s->active_char += sizeof("insert")-1;
			token->opcode = MK_T_INSERT;
			return 0;
		}
#line 1752 "src/parser/scanner.c"
yy179:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy180;
			default:	goto yy120;
			}
yy180:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy181;
			default:	goto yy120;
			}
yy181:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy182;
			}
yy182:
#line 55 "src/parser/scanner.re"
			{
			s->active_char += sizeof("true")-1;
			token->opcode = MK_T_TRUE;
			return 0;
		}
#line 1843 "src/parser/scanner.c"
yy183:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy184;
			default:	goto yy120;
			}
yy184:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy185;
			default:	goto yy120;
			}
yy185:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy186;
			default:	goto yy120;
			}
yy186:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy187;
			}
yy187:
#line 49 "src/parser/scanner.re"
			{
			s->active_char += sizeof("false")-1;
			token->opcode = MK_T_FALSE;
			return 0;
		}
#line 1941 "src/parser/scanner.c"
yy188:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy189;
			default:	goto yy120;
			}
yy189:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy190;
			default:	goto yy120;
			}
yy190:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy119;
			default:	goto yy191;
			}
yy191:
#line 43 "src/parser/scanner.re"
			{
			s->active_char += sizeof("null")-1;
			token->opcode = MK_T_NULL;
			return 0;
		}
#line 2032 "src/parser/scanner.c"
yy192:
			yych = *++YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy195;
			default:	goto yy123;
			}
yy193:
			yyaccept = 0;
			YYMARKER = ++YYCURSOR;
			yych = *YYCURSOR;
yy194:
			switch (yych) {
			case '.':	goto yy192;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy193;
			default:	goto yy5;
			}
yy195:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy195;
			default:	goto yy197;
			}
yy197:
#line 34 "src/parser/scanner.re"
			{
			token->opcode = MK_T_DOUBLE;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 2093 "src/parser/scanner.c"
yy198:
			yych = *++YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':	goto yy199;
			default:	goto yy123;
			}
yy199:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':	goto yy199;
			default:	goto yy5;
			}
yy201:
			++YYCURSOR;
#line 390 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_DECR;
			return 0;
		}
#line 2157 "src/parser/scanner.c"
yy203:
			++YYCURSOR;
#line 330 "src/parser/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_ARROW;
			return 0;
		}
#line 2166 "src/parser/scanner.c"
yy205:
			++YYCURSOR;
#line 252 "src/parser/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SUBASSIGN;
			return 0;
		}
#line 2175 "src/parser/scanner.c"
yy207:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case 'x':	goto yy198;
			default:	goto yy194;
			}
		}
#line 455 "src/parser/scanner.re"

	}

	return status;
}
