#define MK_INSERT                          1
#define MK_INTO                            2
#define MK_IDENTIFIER                      3
#define MK_VALUES                          4
#define MK_PARENTHESES_OPEN                5
#define MK_PARENTHESES_CLOSE               6
#define MK_CREATE                          7
#define MK_COLLECTION                      8
#define MK_COMMA                           9
#define MK_INTEGER                        10
