/* Generated by re2c 0.14.3 on Sat Sep 23 15:48:24 2017 */
#line 1 "src/scanner.re"

#include <string.h>
#include "mk.h"
#include "scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int mk_get_token(mk_scanner_state *s, mk_scanner_token *token) {

	char *q = YYCURSOR, *start = YYCURSOR;
	int status = MK_SCANNER_RETCODE_IMPOSSIBLE;
	int is_constant = 0, j;

	while (MK_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
#line 23 "src/scanner.c"
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy71;
			case '\t':
			case '\r':
			case ' ':	goto yy67;
			case '\n':	goto yy69;
			case '!':	goto yy35;
			case '"':	goto yy17;
			case '$':	goto yy18;
			case '%':	goto yy55;
			case '&':	goto yy37;
			case '\'':	goto yy13;
			case '(':	goto yy21;
			case ')':	goto yy23;
			case '*':	goto yy51;
			case '+':	goto yy49;
			case ',':	goto yy63;
			case '-':	goto yy2;
			case '.':	goto yy57;
			case '/':	goto yy53;
			case '0':	goto yy4;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy6;
			case ':':	goto yy59;
			case ';':	goto yy61;
			case '<':	goto yy43;
			case '=':	goto yy47;
			case '>':	goto yy45;
			case '?':	goto yy65;
			case '@':	goto yy33;
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'G':
			case 'H':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'U':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'g':
			case 'h':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 'u':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy20;
			case 'F':
			case 'f':	goto yy9;
			case 'I':
			case 'i':	goto yy11;
			case 'N':
			case 'n':	goto yy7;
			case 'T':
			case 't':	goto yy10;
			case 'V':
			case 'v':	goto yy12;
			case '[':	goto yy29;
			case '\\':
			case '_':	goto yy19;
			case ']':	goto yy31;
			case '^':	goto yy41;
			case '{':	goto yy25;
			case '|':	goto yy39;
			case '}':	goto yy27;
			case '~':	goto yy15;
			default:	goto yy73;
			}
yy2:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '-':	goto yy171;
			case '0':	goto yy177;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy163;
			case '=':	goto yy175;
			case '>':	goto yy173;
			default:	goto yy3;
			}
yy3:
#line 336 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SUB;
			return 0;
		}
#line 154 "src/scanner.c"
yy4:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case 'x':	goto yy168;
			default:	goto yy164;
			}
yy5:
#line 24 "src/scanner.re"
			{
			token->opcode = MK_T_INTEGER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 172 "src/scanner.c"
yy6:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			goto yy164;
yy7:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case 'U':
			case 'u':	goto yy158;
			default:	goto yy117;
			}
yy8:
#line 111 "src/scanner.re"
			{
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			token->opcode = MK_T_IDENTIFIER;
			return 0;
		}
#line 194 "src/scanner.c"
yy9:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy153;
			default:	goto yy117;
			}
yy10:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy149;
			default:	goto yy117;
			}
yy11:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy140;
			default:	goto yy117;
			}
yy12:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy134;
			default:	goto yy117;
			}
yy13:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych >= 0x01) goto yy130;
yy14:
#line 426 "src/scanner.re"
			{
			status = MK_SCANNER_RETCODE_ERR;
			break;
		}
#line 233 "src/scanner.c"
yy15:
			yyaccept = 2;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case '"':	goto yy124;
			default:	goto yy16;
			}
yy16:
#line 168 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_NOT;
			return 0;
		}
#line 248 "src/scanner.c"
yy17:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy14;
			goto yy119;
yy18:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy116;
			default:	goto yy14;
			}
yy19:
			yych = *++YYCURSOR;
			goto yy117;
yy20:
			yych = *++YYCURSOR;
			goto yy117;
yy21:
			++YYCURSOR;
#line 120 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_PARENTHESES_OPEN;
			return 0;
		}
#line 327 "src/scanner.c"
yy23:
			++YYCURSOR;
#line 126 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_PARENTHESES_CLOSE;
			return 0;
		}
#line 336 "src/scanner.c"
yy25:
			++YYCURSOR;
#line 132 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BRACKET_OPEN;
			return 0;
		}
#line 345 "src/scanner.c"
yy27:
			++YYCURSOR;
#line 138 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BRACKET_CLOSE;
			return 0;
		}
#line 354 "src/scanner.c"
yy29:
			++YYCURSOR;
#line 144 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SBRACKET_OPEN;
			return 0;
		}
#line 363 "src/scanner.c"
yy31:
			++YYCURSOR;
#line 150 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SBRACKET_CLOSE;
			return 0;
		}
#line 372 "src/scanner.c"
yy33:
			++YYCURSOR;
#line 156 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_AT;
			return 0;
		}
#line 381 "src/scanner.c"
yy35:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy112;
			default:	goto yy36;
			}
yy36:
#line 162 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_NOT;
			return 0;
		}
#line 395 "src/scanner.c"
yy37:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '&':	goto yy110;
			default:	goto yy38;
			}
yy38:
#line 186 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_AND;
			return 0;
		}
#line 409 "src/scanner.c"
yy39:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '|':	goto yy108;
			default:	goto yy40;
			}
yy40:
#line 192 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_OR;
			return 0;
		}
#line 423 "src/scanner.c"
yy41:
			++YYCURSOR;
#line 198 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_BITWISE_XOR;
			return 0;
		}
#line 432 "src/scanner.c"
yy43:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '<':	goto yy106;
			case '=':	goto yy104;
			default:	goto yy44;
			}
yy44:
#line 294 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_LESS;
			return 0;
		}
#line 447 "src/scanner.c"
yy45:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy100;
			case '>':	goto yy102;
			default:	goto yy46;
			}
yy46:
#line 300 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_GREATER;
			return 0;
		}
#line 462 "src/scanner.c"
yy47:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy96;
			case '>':	goto yy94;
			default:	goto yy48;
			}
yy48:
#line 216 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_ASSIGN;
			return 0;
		}
#line 477 "src/scanner.c"
yy49:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '+':	goto yy90;
			case '=':	goto yy92;
			default:	goto yy50;
			}
yy50:
#line 330 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_ADD;
			return 0;
		}
#line 492 "src/scanner.c"
yy51:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy88;
			default:	goto yy52;
			}
yy52:
#line 342 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MUL;
			return 0;
		}
#line 506 "src/scanner.c"
yy53:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy86;
			default:	goto yy54;
			}
yy54:
#line 348 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DIV;
			return 0;
		}
#line 520 "src/scanner.c"
yy55:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy84;
			default:	goto yy56;
			}
yy56:
#line 354 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MOD;
			return 0;
		}
#line 534 "src/scanner.c"
yy57:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '.':	goto yy78;
			case '=':	goto yy80;
			default:	goto yy58;
			}
yy58:
#line 324 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DOT;
			return 0;
		}
#line 549 "src/scanner.c"
yy59:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case ':':	goto yy76;
			default:	goto yy60;
			}
yy60:
#line 384 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_COLON;
			return 0;
		}
#line 563 "src/scanner.c"
yy61:
			++YYCURSOR;
#line 390 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DOTCOMMA;
			return 0;
		}
#line 572 "src/scanner.c"
yy63:
			++YYCURSOR;
#line 396 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_COMMA;
			return 0;
		}
#line 581 "src/scanner.c"
yy65:
			++YYCURSOR;
#line 402 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_QUESTION;
			return 0;
		}
#line 590 "src/scanner.c"
yy67:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy75;
yy68:
#line 408 "src/scanner.re"
			{
			s->active_char += (YYCURSOR - start);
			token->opcode = MK_T_IGNORE;
			return 0;
		}
#line 602 "src/scanner.c"
yy69:
			++YYCURSOR;
#line 414 "src/scanner.re"
			{
			s->active_line++;
			s->active_char = 0;
			token->opcode = MK_T_IGNORE;
			return 0;
		}
#line 612 "src/scanner.c"
yy71:
			++YYCURSOR;
#line 421 "src/scanner.re"
			{
			status = MK_SCANNER_RETCODE_EOF;
			break;
		}
#line 620 "src/scanner.c"
yy73:
			yych = *++YYCURSOR;
			goto yy14;
yy74:
			++YYCURSOR;
			yych = *YYCURSOR;
yy75:
			switch (yych) {
			case '\t':
			case '\r':
			case ' ':	goto yy74;
			default:	goto yy68;
			}
yy76:
			++YYCURSOR;
#line 318 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_DOUBLECOLON;
			return 0;
		}
#line 642 "src/scanner.c"
yy78:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '.':	goto yy82;
			default:	goto yy79;
			}
yy79:
#line 372 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_INCLUSIVE_RANGE;
			return 0;
		}
#line 656 "src/scanner.c"
yy80:
			++YYCURSOR;
#line 252 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_CONCATASSIGN;
			return 0;
		}
#line 665 "src/scanner.c"
yy82:
			++YYCURSOR;
#line 378 "src/scanner.re"
			{
			s->active_char += 3;
			token->opcode = MK_T_EXCLUSIVE_RANGE;
			return 0;
		}
#line 674 "src/scanner.c"
yy84:
			++YYCURSOR;
#line 246 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MODASSIGN;
			return 0;
		}
#line 683 "src/scanner.c"
yy86:
			++YYCURSOR;
#line 240 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_DIVASSIGN;
			return 0;
		}
#line 692 "src/scanner.c"
yy88:
			++YYCURSOR;
#line 234 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_MULASSIGN;
			return 0;
		}
#line 701 "src/scanner.c"
yy90:
			++YYCURSOR;
#line 360 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_INCR;
			return 0;
		}
#line 710 "src/scanner.c"
yy92:
			++YYCURSOR;
#line 222 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_ADDASSIGN;
			return 0;
		}
#line 719 "src/scanner.c"
yy94:
			++YYCURSOR;
#line 312 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_DOUBLEARROW;
			return 0;
		}
#line 728 "src/scanner.c"
yy96:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy98;
			default:	goto yy97;
			}
yy97:
#line 258 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_EQUALS;
			return 0;
		}
#line 742 "src/scanner.c"
yy98:
			++YYCURSOR;
#line 270 "src/scanner.re"
			{
			s->active_char += 3;
			token->opcode = MK_T_IDENTICAL;
			return 0;
		}
#line 751 "src/scanner.c"
yy100:
			++YYCURSOR;
#line 288 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_GREATEREQUAL;
			return 0;
		}
#line 760 "src/scanner.c"
yy102:
			++YYCURSOR;
#line 210 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_BITWISE_SHIFTRIGHT;
			return 0;
		}
#line 769 "src/scanner.c"
yy104:
			++YYCURSOR;
#line 282 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_LESSEQUAL;
			return 0;
		}
#line 778 "src/scanner.c"
yy106:
			++YYCURSOR;
#line 204 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_BITWISE_SHIFTLEFT;
			return 0;
		}
#line 787 "src/scanner.c"
yy108:
			++YYCURSOR;
#line 180 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_OR;
			return 0;
		}
#line 796 "src/scanner.c"
yy110:
			++YYCURSOR;
#line 174 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_AND;
			return 0;
		}
#line 805 "src/scanner.c"
yy112:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy114;
			default:	goto yy113;
			}
yy113:
#line 264 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_NOTEQUALS;
			return 0;
		}
#line 819 "src/scanner.c"
yy114:
			++YYCURSOR;
#line 276 "src/scanner.re"
			{
			s->active_char += 3;
			token->opcode = MK_T_NOTIDENTICAL;
			return 0;
		}
#line 828 "src/scanner.c"
yy116:
			++YYCURSOR;
			yych = *YYCURSOR;
yy117:
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy116;
			default:	goto yy8;
			}
yy118:
			++YYCURSOR;
			yych = *YYCURSOR;
yy119:
			switch (yych) {
			case 0x00:	goto yy120;
			case '"':	goto yy122;
			case '\\':	goto yy121;
			default:	goto yy118;
			}
yy120:
			YYCURSOR = YYMARKER;
			switch (yyaccept) {
			case 0: 	goto yy5;
			case 1: 	goto yy14;
			default:	goto yy16;
			}
yy121:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy120;
			default:	goto yy118;
			}
yy122:
			++YYCURSOR;
#line 100 "src/scanner.re"
			{
			token->opcode = MK_T_STRING;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 935 "src/scanner.c"
yy124:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy120;
			case '"':	goto yy127;
			case '\\':	goto yy126;
			default:	goto yy124;
			}
yy126:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy120;
			default:	goto yy124;
			}
yy127:
			++YYCURSOR;
#line 90 "src/scanner.re"
			{
			token->opcode = MK_T_ISTRING;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 963 "src/scanner.c"
yy129:
			++YYCURSOR;
			yych = *YYCURSOR;
yy130:
			switch (yych) {
			case 0x00:	goto yy120;
			case '\'':	goto yy132;
			case '\\':	goto yy131;
			default:	goto yy129;
			}
yy131:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy120;
			default:	goto yy129;
			}
yy132:
			++YYCURSOR;
#line 80 "src/scanner.re"
			{
			token->opcode = MK_T_CHAR;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 992 "src/scanner.c"
yy134:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy135;
			default:	goto yy117;
			}
yy135:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy136;
			default:	goto yy117;
			}
yy136:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy137;
			default:	goto yy117;
			}
yy137:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy138;
			default:	goto yy117;
			}
yy138:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy116;
			default:	goto yy139;
			}
yy139:
#line 73 "src/scanner.re"
			{
			s->active_char += sizeof("values")-1;
			token->opcode = MK_T_VALUES;
			return 0;
		}
#line 1097 "src/scanner.c"
yy140:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy141;
			case 'T':
			case 't':	goto yy142;
			default:	goto yy117;
			}
yy141:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy145;
			default:	goto yy117;
			}
yy142:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy143;
			default:	goto yy117;
			}
yy143:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy116;
			default:	goto yy144;
			}
yy144:
#line 67 "src/scanner.re"
			{
			s->active_char += sizeof("into")-1;
			token->opcode = MK_T_INTO;
			return 0;
		}
#line 1197 "src/scanner.c"
yy145:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy146;
			default:	goto yy117;
			}
yy146:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy147;
			default:	goto yy117;
			}
yy147:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy116;
			default:	goto yy148;
			}
yy148:
#line 61 "src/scanner.re"
			{
			s->active_char += sizeof("insert")-1;
			token->opcode = MK_T_INSERT;
			return 0;
		}
#line 1288 "src/scanner.c"
yy149:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy150;
			default:	goto yy117;
			}
yy150:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy151;
			default:	goto yy117;
			}
yy151:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy116;
			default:	goto yy152;
			}
yy152:
#line 55 "src/scanner.re"
			{
			s->active_char += sizeof("true")-1;
			token->opcode = MK_T_TRUE;
			return 0;
		}
#line 1379 "src/scanner.c"
yy153:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy154;
			default:	goto yy117;
			}
yy154:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy155;
			default:	goto yy117;
			}
yy155:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy156;
			default:	goto yy117;
			}
yy156:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy116;
			default:	goto yy157;
			}
yy157:
#line 49 "src/scanner.re"
			{
			s->active_char += sizeof("false")-1;
			token->opcode = MK_T_FALSE;
			return 0;
		}
#line 1477 "src/scanner.c"
yy158:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy159;
			default:	goto yy117;
			}
yy159:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy160;
			default:	goto yy117;
			}
yy160:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy116;
			default:	goto yy161;
			}
yy161:
#line 43 "src/scanner.re"
			{
			s->active_char += sizeof("null")-1;
			token->opcode = MK_T_NULL;
			return 0;
		}
#line 1568 "src/scanner.c"
yy162:
			yych = *++YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy165;
			default:	goto yy120;
			}
yy163:
			yyaccept = 0;
			YYMARKER = ++YYCURSOR;
			yych = *YYCURSOR;
yy164:
			switch (yych) {
			case '.':	goto yy162;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy163;
			default:	goto yy5;
			}
yy165:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy165;
			default:	goto yy167;
			}
yy167:
#line 34 "src/scanner.re"
			{
			token->opcode = MK_T_DOUBLE;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
#line 1629 "src/scanner.c"
yy168:
			yych = *++YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':	goto yy169;
			default:	goto yy120;
			}
yy169:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':	goto yy169;
			default:	goto yy5;
			}
yy171:
			++YYCURSOR;
#line 366 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_DECR;
			return 0;
		}
#line 1693 "src/scanner.c"
yy173:
			++YYCURSOR;
#line 306 "src/scanner.re"
			{
			s->active_char += 2;
			token->opcode = MK_T_ARROW;
			return 0;
		}
#line 1702 "src/scanner.c"
yy175:
			++YYCURSOR;
#line 228 "src/scanner.re"
			{
			s->active_char++;
			token->opcode = MK_T_SUBASSIGN;
			return 0;
		}
#line 1711 "src/scanner.c"
yy177:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case 'x':	goto yy168;
			default:	goto yy164;
			}
		}
#line 431 "src/scanner.re"

	}

	return status;
}
